#!/usr/bin/env bash
#
# setup-hooks.sh — T34.5
# One-time installer. After running this once, every `git commit` will
# auto-run deploy.sh — meaning index.html, manifest.json, and sw.js are
# always in sync with the source files at push time.
#
# Uses the modern `git config core.hooksPath` approach so the hooks live
# inside the repo (under .githooks/) and are tracked. No copying to .git/.
#
# Run from the project root:
#   chmod +x setup-hooks.sh deploy.sh
#   ./setup-hooks.sh
#
# To uninstall later: git config --unset core.hooksPath

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

HOOKS_DIR=".githooks"

# Ensure we're inside a git repo
if ! git rev-parse --git-dir > /dev/null 2>&1; then
  echo "✗ Not a git repository. Run from inside the ARISE repo."
  exit 1
fi

# Create the hooks directory + the pre-commit hook
mkdir -p "$HOOKS_DIR"

cat > "$HOOKS_DIR/pre-commit" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by setup-hooks.sh — runs deploy.sh on every commit.
# If deploy.sh exits non-zero (e.g. smoke test regression), the commit is
# aborted so we never ship a broken build.
set -e
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
cd "$SCRIPT_DIR"
if [ -x ./deploy.sh ]; then
  ./deploy.sh
else
  echo "  (deploy.sh missing or not executable — skipping auto-sync)"
fi
EOF

chmod +x "$HOOKS_DIR/pre-commit"
chmod +x deploy.sh 2>/dev/null || true

# Point git at .githooks/ for this clone
git config core.hooksPath "$HOOKS_DIR"

echo "✓ Hooks installed."
echo ""
echo "  From now on, every git commit will auto-sync index.html and run"
echo "  smoke tests. To bypass once: git commit --no-verify"
echo "  To disable permanently:     git config --unset core.hooksPath"
